### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Xav83130** [Denvi/grblControl#11]
Hi,
I did the translation in French, but I do not know how to push it on the Git.
I have not your email address to send it.
can you help me ?

**Comment by Denvi** [comment]
Just press green button left to "branch" selector in Your forked repository, button has tooltip: "Compare, review, create a pull request".
Then press "Create pull request" button.

**Comment by Xav83130** [comment]
I think it's good?
grbl Control is really simple and effective good job.
Thank you for sharing.

**Comment by Denvi** [comment]
Don't see any pull request.

**Comment by Denvi** [comment]
Added. Thank you.
You can test it with last binary file for windows from "bin" folder & "grblControl_fr.qm", "qt_fr.qm" files copied to "translations" directory.

**Comment by Xav83130** [comment]
with pleasure,
I am under linux, and I'm not very good for "compiling".
I am looking forward that you compile the linux version for testing.

**Comment by Denvi** [comment]
Check linux binary in "bin" directory: [grblControl](https://github.com/Denvi/grblControl/blob/master/bin/grblControl)

**Comment by Xav83130** [comment]
ok I've experienced in my work with windows.
I saw a few small mistakes.
I correct in the evening.

**Comment by Xav83130** [comment]
It seems to me better.
Sorry for the inconvenience.
See you soon

**Comment by Xav83130** [comment]
Hi,
Translation look pretty good, I transmits the info on some French forum.
to see if there are bugs.
nothing to see, but would it be to you to have the updated version of linux with the latest changes more regularly?
thank you very much for your work.

**Comment by Xav83130** [comment]
Hello,
I am looking for the meaning of "Zb" and "Zt"?
if someone an idea.

**Comment by Denvi** [comment]
Zb - Z-bottom coordinate for heightmap probing;
Zt - Z-top.
Also one more new line is added to the program. Check *.ts file please. Thanks.

**Comment by Xav83130** [comment]
Ok it looks good.

**Comment by Xav83130** [comment]
Hi,
For this, "(used in visualizer and heightmap modification procedure)"

I understand "used in visualizer and heightmap"  but i don't understand this "modification procedure" if you explain?

**Comment by Denvi** [comment]
This refers to the procedure of converting a file using the height map.
I rewrite this string later in a more understandable form.

**Comment by Xav83130** [comment]
I added the translation, but I can not send, permissions problem with git.

**Comment by Denvi** [comment]
Hello, explain, what the exact problem is?

**Comment by Xav83130** [comment]
When i commit with GitHub i have this message.
With other Git i don't have problem.
![commit bug](http://pix.slic.it/p/5sf)

**Comment by Xav83130** [comment]
I'm really bad with Git
I succeeded but not without difficulty.
I especially hope not to do anything.
A ++
