### ISSUE TITLE
Jog positioning

### ISSUE THREAD

**Issue by Xav83130** [Denvi/grblControl#18]
Hi,
In full screen, the buttons of the manual control (Jog) are partially hidden.
would it be possible to improve this?
here is a picture: http://pix.slic.it/p/5hr
Thanks

**Comment by pihnat** [comment]
You may have to use a smaller font size or increase screen resolution.
On a laptop with 1366x768 screen I start losing jog buttons with font size of 10 or higher but all is OK with 8 & 9 font size.
On my desktop computer with 1680x1050 screen there's no problem with font size of 12 - all jog buttons are fully visible.

**Comment by Denvi** [comment]
I can decrease console window minimum height:

![jog_keys3](https://cloud.githubusercontent.com/assets/5119037/11300522/b42ba3fe-8fb1-11e5-8470-cc29b5c6c8c6.png)

**Comment by Xav83130** [comment]
may be given the opportunity to increase / decrease the console window:
![increase/decrease](http://pix.slic.it/p/5ij)

**Comment by Denvi** [comment]
Commited this:

![grblconsole1](https://cloud.githubusercontent.com/assets/5119037/11446800/19f12dec-955e-11e5-9107-6ae3a3019186.gif)

**Comment by Xav83130** [comment]
Perfect! I look forward to testing.
Thx

**Comment by Denvi** [comment]
Added binaries for flicker-free version:

![grblconsole2](https://cloud.githubusercontent.com/assets/5119037/11473758/2621a076-9796-11e5-8d65-8b99779aaac7.gif)

**Comment by Xav83130** [comment]
Even better ... thank you.
I regret not knowing compile .... to enjoy this change. ;-)

**Comment by Denvi** [comment]
Just copy file from binaries to program folder:

[Binaries here](https://github.com/Denvi/grblControl/tree/master/bin)

linux: [grblControl](https://github.com/Denvi/grblControl/tree/master/bin/grblControl)
windows: [grblControl.exe](https://github.com/Denvi/grblControl/tree/master/bin/grblControl.exe)

**Comment by Xav83130** [comment]
Ok I tested, I find it very well.
Thank you
