### ISSUE TITLE
Compiling problem 

### ISSUE THREAD

**Issue by losmichal** [Denvi/grblControl#19]
Hi

I'm try to compile this in Qt but still geting lot of error can you please tell me what compiler you are using. I try VC++8 and VC++14 but with lot of error 
![scr1](https://cloud.githubusercontent.com/assets/16061590/11453384/309fa1b2-9609-11e5-9956-7ed242b45215.jpg)

**Comment by Denvi** [comment]
Hi, i'm using MinGW compiler.

**Comment by losmichal** [comment]
Hi

Thank you for quick replay.
I have add MinGW 4.9.2 32bit and it has compile with lot of Warning, it's run but with about Visualization 
Can you please help me with this ??

![scr2](https://cloud.githubusercontent.com/assets/16061590/11456873/6e981294-9698-11e5-9fc1-95a5de6eb51c.png)
![scr3](https://cloud.githubusercontent.com/assets/16061590/11456891/bca49b1a-9698-11e5-8e09-681cf92c5857.jpg)

**Comment by Denvi** [comment]
It is possible not to pay attention to warnings, it's just about unused variables.
Visualizer & table have to be adjusted.
Visualizer can be fixed with "Set to defaults" button on settings form.
Table - with proper settings file (you can copy "settings.ini" file from last release archive to program build folder).

**Comment by losmichal** [comment]
Thank You it's work :)
I'm going to translate it, do i have to change all label name etc. or i can add another language

**Comment by Denvi** [comment]
1) In .pro file declare your translation in "TRANSLATIONS += ..." string (use ISO 639 for name suffix).
2) Create .ts file with "lupdate" command from "Tools > External > Linguist" menu.
3) Make translation by editing .ts file with "Linguist" app or other text editor.
4) Compile .qm translation file with "lrelease" command from "Tools > External > Linguist" menu in "Qt creator" app.
5) Copy .qm file to "translations" directory of "grblControl" app build/run folder.
