### ISSUE TITLE
aborting send program without homing enabled.

### ISSUE THREAD

**Issue by DEF7** [Denvi/grblControl#27]
grblControl fucking rocks, first of all. I just built my X-Carve (waiting for spindle) but I've only been testing it out with my personally modified version of grblControl that runs in imperial, and with a few graphical and keyboard jogging changes.. I will probably not bother using any other GRBL controller program with it because grblControl is *exactly* what I would make if I were to write my own program from scratch (which I was just about to do when I discovered grblControl).

so, I don't have homing switches on my machine, or homing enabled on GRBL, so 'home' is just floating wherever (somewhere outside my house, apparently)

when I run a program and hit the abort button, it seems to perform the Restore XYZ button's function (I assume) and sends the machine off wherever it thinks it should go. What would be great is if the abort button just sent the machine back to wherever it was when it started the program that it was running in the first place, perhaps moving to safety Z first and then rapiding to the original start position.

I'm going to try to hack away at the code and figure this out myself but I figured I may as well contribute my ideas to the project for the project's benefit as a whole.

thanks for sharing grblControl with us, I am working on a project that uses G-code programs with tens of thousands of lines of code, and all the other programs I have tried came to a crawl when I would load my G-code program into them because they were written using tons of external garbage and weren't running natively on my CPU.

please keep up on grblControl! I have been promoting it on various forums telling people it is the best program I have found, because it is true! With the heightmapping feature you're right up there with the best of the other programs.

email me if you want to have some conversations and I'll collaborate because I think grblControl is so extremely close to becoming a 'gold standard' sort of program for GRBL CNCs and I have plenty of professional precision CNC manufacturing experience to contribute, as well as two decades of C programming to help see things through.

radioteeth@gmail.com

**Comment by Denvi** [comment]
Many thanks for a good response, glad to try further.

"Abort" function was discussed in issue [#10](https://github.com/Denvi/grblControl/issues/10)
In "two worlds" it's working as follows:

1) "Send" button stores "G92" offsets.
2) "Abort" button sends "Pause" command.
3) Program waits until machine coordinates become invariable.
4) Program moves tools to current machine position to avoid rounding errors.
5) Program restores "G92" offsets.

So, if you have not desirable behavior, look for p. 4.
It's "restoreOffsets()" function in "frmMain.cpp" source file.

**Comment by DEF7** [comment]
Ok, I figured out that the problem was with my hacked grblControl that I tried to convert into operating in inches instead of millimeters.

The m_storedX/Y/Z (and probably many other values) were being multiplied by 25.4 by the toMetric() function, which was causing things like RestoreXYZ and Abort to send the machine into space.

Clearly I have failed to make an imperial version of grblControl.

What is the easiest way to make grblControl run in inches? I have discovered all of the G21 commands, and replaced them with G20, and have made a few other little changes, but it seems that metric is woven deep in grblControl.

Thank you!

**Comment by Denvi** [comment]
I am going to add imperial units as an option in the next version of the program.
Couldn't help you at this moment, at least because, I don't know how you changed the program.
As far as I remember, toMetric() function used only to handle imperial units from grbl status string.
Offsets stored in metric units, so you should use "G21" command to restore them.
I will deal with this problem more densely in couple of days.

**Comment by DEF7** [comment]
I see. I have GRBL running in G20, so everything is being reported in inches, and in the toMetric function it's multiplying everything by 25.4 for the internal conversion back to millimeters so for my version I just had to swap the logic. I'm pretty sure that if m_settings.units was set to metric my version would not work correctly anyway. Thanks!

**Comment by kquaid** [comment]
I am having similar problems with my non-homing x-carve and wanted to add to the conversation.  

I really love grblControl, but the Abort button is blocking me at the moment.

When I am testing something and I have to pause, it usually means something has gone wrong.  A bit broke or my settings were bad or what not.  I don't want to ruin my work piece, so I hit "Abort" hoping I can save everything.  Suddenly grblControl tells my x-carve to go very far away.  I really just wish it would abort sending and do nothing else.  I can then use the UI to raise the bit and see what went wrong.

But maybe most people like the current actions when Abort is pressed, so a solution could be to customize the g-code commands in settings.  Most people could leave the default Abort commands in there, and some people like me could just tell the machine to stop and turn off the spindle.  (Plus, doing it this way makes it easier for non-programmers to tweak)

Thank you!  This software is so great!

**Comment by Denvi** [comment]
Hello.

>  Suddenly grblControl tells my x-carve to go very far away

Looks like it's a bug. So, please, post:
1) GRBL firmware version.
2) grblControl program version you using.
3) Simple sample G-code program which cause "Abort" button to work wrong.
4) grblControl window screenshots before sending G-code program and after pressing "Abort" button.

**Comment by pihnat** [comment]
Hi everyone,
I raised the initial Abort issue in #10 and since it was implemented I've never seen the problem described above - when pressing Abort the CNC machine just stops dead.
Please post the info Denvi requested so the fault can be checked.

**Comment by kquaid** [comment]
Very sorry, I wasn't able to get over to my workshop and connect directly to the machine again until today.  Here is what I have:

1) GRBL 0.9i
2) grblControl 0.8.1
3) Attached is a sample NC file I am getting out of VisualCam.  I am using the Mach3 post processor.
4) Attached is a before and after shot of the Console output.  You can see that after hitting Abort it sends 2 more move commands before stopping.

If it is helpful at all, I have noticed that the offset of the last 2 moves is relative to where I pause the program.  It always seems to go the same distance in X Y and Z away from my position at Abort.

[circletest.zip](https://github.com/Denvi/grblControl/files/84161/circletest.zip)
![grblcontrol_abort](https://cloud.githubusercontent.com/assets/16582400/12222435/a587ab30-b7bc-11e5-8538-5d1e224c35da.jpg)

Thanks!

**Comment by pihnat** [comment]
OK it took a while but I can now duplicate the behaviour you describe. It is because of the values in G54 offset coords. I have values of 0,0,0, yours are -8.923,-269.586,22.000. grblControl seems to jump by the offset amount when Abort is pressed. Denvi, is this correct behaviour?

Zero the offsets in G54 by sending  $RST#  to grbl and see how that goes.

**Comment by kquaid** [comment]
I am trying everything here and I can not clear G54.  Using $RST# returns "error: Bad number format".  Any reset command from the grbl Wiki does the same, whether I send from grblControl or any serial connection.

It looks like I need to reflash with 0.9j, but then I might not be able to use the x-carve software anymore.

**Comment by pihnat** [comment]
Sorry my mistake. The command is  $RST=#
Don't use the other reset commands just this one. The others clear too many settings.
Reference is  https://github.com/grbl/grbl/wiki/Configuring-Grbl-v0.9

**Comment by kquaid** [comment]
I tried that one, too.  And $RST=* and $RST=$.  They all gave me the same error and did nothing.

The command has changed from 0.9i to 0.9j, but I can't find anything online that says what the correct command is for 0.9i.

**Comment by pihnat** [comment]
I flashed with 0.9i and it did accept the RST command. I'll freshly download it and will try again.

**Comment by pihnat** [comment]
With grbl 0.9i, I sent command from grblControl and it works.


![g54 reset](https://cloud.githubusercontent.com/assets/15223225/12246673/e64f5bde-b903-11e5-8fc2-ba13d772af69.jpg)

**Comment by kquaid** [comment]
Wow, that is just not what I get.  Crazy.

I guess I'll reflash it.  I just hope I get all of the correct settings in there again once it is reflashed.  It seems like some people get new problems when they do this.

Thanks for your help!

**Comment by pihnat** [comment]
I used Putty to list my settings and then I did a screen grab and saved as jpg. That way I can always go back to see what they are.
All the best.

**Comment by kquaid** [comment]
Good idea.  I'll give it a try.

Thanks!

**Comment by Denvi** [comment]
```
G10 L2 X0 Y0 Z0
```

To clear G54 offsets.

**Comment by kquaid** [comment]
That fixed it!  All of the offsets are 0, 0, 0 and it stops in place correctly when pressing the Abort button.

So nothing was wrong with grblControl after all.  I look forward to making a lot of cool stuff with this great program.  Thank you all for your help!

**Comment by Denvi** [comment]
In fact, G54 offsets as well as others should not affect the functionality of the "Abort" button. Marked as "Bug".

**Comment by pavelgrigorov** [comment]
Good day ! a very good program works fine you're done! previously I enjoyed JCNC but downloaded this program and I do not want to work more in the other ! Only I've got a problem , how to set the ratio of pitch to millimeters ? step / mm ??? for example I have the x-axis and y-axis and the z- belt drive stud or different ratio steps that X and Y do please answer would be very grateful ! thanks in advance !!! and if you can throw off please reply to mail pavelgrigorov893@gmail.com

**Comment by pavelgrigorov** [comment]
Good day ! Denvi a very good program works fine you're done! previously I enjoyed JCNC but downloaded this program and I do not want to work more in the other ! Only I've got a problem , how to set the ratio of pitch to millimeters ? step / mm ??? for example I have the x-axis and y-axis and the z- belt drive stud or different ratio steps that X and Y do please answer would be very grateful ! thanks in advance !!! and if you can throw off please reply to mail pavelgrigorov893@gmail.com

**Comment by Denvi** [comment]
Hi, "step/mm" is a firmware settings.
You can use "$$" command in console to see current GRBL settings:
~~~
$$ < $0=10 (step pulse, usec)
$1=255 (step idle delay, msec)
$2=0 (step port invert mask:00000000)
$3=5 (dir port invert mask:00000101)
$4=0 (step enable invert, bool)
$5=0 (limit pins invert, bool)
$6=0 (probe pin invert, bool)
$10=3 (status report mask:00000011)
$11=0.050 (junction deviation, mm)
$12=0.002 (arc tolerance, mm)
$13=0 (report inches, bool)
$14=1 (auto start, bool)
$20=0 (soft limits, bool)
$21=0 (hard limits, bool)
$22=1 (homing cycle, bool)
$23=0 (homing dir invert mask:00000000)
$24=25.000 (homing feed, mm/min)
$25=250.000 (homing seek, mm/min)
$26=250 (homing debounce, msec)
$27=1.000 (homing pull-off, mm)
$100=800.000 (x, step/mm)
$101=800.000 (y, step/mm)
$102=320.000 (z, step/mm)
...
~~~

To change "step/mm" parameter of X-axis, for example, use command:
~~~
$100=400
~~~

**Comment by pavelgrigorov** [comment]
Thank you very much! I understood) would not be bad to add this in the
settings to your program has become even more convenient !! you're
cool !!!!


2016-02-12 16:23 GMT+03:00 Denvi <notifications@github.com>:

**Comment by pavelgrigorov** [comment]
и еще бы неплохо добавить  линейку

2016-02-12 16:34 GMT+03:00 Павел Григоров <pavelgrigorov893@gmail.com>:

**Comment by Denvi** [comment]
Создайте новый вопрос (new issue) (вопросы) с подробным описанием предложений. Будет время - займусь. Эта тема немного про другое.

**Comment by pavelgrigorov** [comment]
у меня переводчик плохо работает! что это значит ??


2016-02-19 18:09 GMT+03:00 Denvi <notifications@github.com>:

**Comment by pavelgrigorov** [comment]
доброго времени суток! я хотел попросить у вас помощи с этим кодом для
ардуино Gy 521 and stepper motor!   я буду очень рад если вы мне поможете


https://www.youtube.com/watch?v=2pbVtUTsgjk



Blocking.pde: In function 'void setup()':

Blocking.pde:75:42: error: 'i2cWrite' was not declared in this scope

Blocking.pde:76:35: error: 'i2cWrite' was not declared in this scope

Blocking.pde:78:34: error: 'i2cRead' was not declared in this scope

Blocking.pde:87:34: error: 'i2cRead' was not declared in this scope

Blocking.pde: In function 'void loop()':

Blocking.pde:133:35: error: 'i2cRead' was not declared in this scope

Ошибка компиляции.
в чем может быть проблема  ???

#include <AccelStepper.h>
#include <Wire.h>
#include "Kalman.h"


#define RESTRICT_PITCH

Kalman kalmanX;
Kalman kalmanY;

///////////stepeer

AccelStepper stepper1(1, 9, 8);

AccelStepper stepper2(1, 7, 6);
int pos = 2000;
//int cantidad = 7;
int addr = 0;


// Define our three input button pins
#define  LEFT_PIN  4
#define  STOP_PIN  3
#define  RIGHT_PIN 5
#define  CONTROL_PIN 11

#define  SPEED_PIN 0

int velocidad = 1000;
int cantidad = 6;
int aceleracion = 500;



/* IMU Data */
double accX, accY, accZ;
double gyroX, gyroY, gyroZ;
int16_t tempRaw;

double gyroXangle, gyroYangle; // Angle calculate using the gyro only
double compAngleX, compAngleY; // Calculated angle using a complementary
filter
double kalAngleX, kalAngleY; // Calculated angle using a Kalman filter

uint32_t timer;
uint8_t i2cData[14]; // Buffer for I2C data

// TODO: Make calibration routine

void setup() {
   pinMode(LEFT_PIN, INPUT_PULLUP);
  pinMode(STOP_PIN, INPUT_PULLUP);
  pinMode(RIGHT_PIN, INPUT_PULLUP);
    pinMode(CONTROL_PIN, INPUT_PULLUP);



  Serial.begin(115200);
  Wire.begin();




  TWBR = ((F_CPU / 400000L) - 16) / 2; // Set I2C frequency to 400kHz

 stepper1.setMaxSpeed(3000);
  stepper2.setMaxSpeed(3000);

    stepper1.setAcceleration(500);
      stepper2.setAcceleration(500);

  i2cData[0] = 7; // Set the sample rate to 1000Hz - 8kHz/(7+1) = 1000Hz
  i2cData[1] = 0x00; // Disable FSYNC and set 260 Hz Acc filtering, 256 Hz
Gyro filtering, 8 KHz sampling
  i2cData[2] = 0x00; // Set Gyro Full Scale Range to ±250deg/s
  i2cData[3] = 0x00; // Set Accelerometer Full Scale Range to ±2g
  while (i2cWrite(0x19, i2cData, 4, false)); // Write to all four registers
at once
  while (i2cWrite(0x6B, 0x01, true)); // PLL with X axis gyroscope
reference and disable sleep mode

  while (i2cRead(0x75, i2cData, 1));
  if (i2cData[0] != 0x68) { // Read "WHO_AM_I" register
    Serial.print(F("Error reading sensor"));
    while (1);
  }

  delay(100); // Wait for sensor to stabilize

  /* Set kalman and gyro starting angle */
  while (i2cRead(0x3B, i2cData, 6));
  accX = (i2cData[0] << 8) | i2cData[1];
  accY = (i2cData[2] << 8) | i2cData[3];
  accZ = (i2cData[4] << 8) | i2cData[5];


#ifdef RESTRICT_PITCH // Eq. 25 and 26
  double roll  = atan2(accY, accZ) * RAD_TO_DEG;
  double pitch = atan(-accX / sqrt(accY * accY + accZ * accZ)) * RAD_TO_DEG;
#else // Eq. 28 and 29
  double roll  = atan(accY / sqrt(accX * accX + accZ * accZ)) * RAD_TO_DEG;
  double pitch = atan2(-accX, accZ) * RAD_TO_DEG;
#endif

  kalmanX.setAngle(roll); // Set starting angle
  kalmanY.setAngle(pitch);
  gyroXangle = roll;
  gyroYangle = pitch;
  compAngleX = roll;
  compAngleY = pitch;


}


/////////////////7

///////////////7







void loop() {


//////

/////




  /* Update all the values */
  while (i2cRead(0x3B, i2cData, 14));
  accX = ((i2cData[0] << 8) | i2cData[1]);
  accY = ((i2cData[2] << 8) | i2cData[3]);
  accZ = ((i2cData[4] << 8) | i2cData[5]);
  tempRaw = (i2cData[6] << 8) | i2cData[7];
  gyroX = (i2cData[8] << 8) | i2cData[9];
  gyroY = (i2cData[10] << 8) | i2cData[11];
  gyroZ = (i2cData[12] << 8) | i2cData[13];

  double dt = (double)(micros() - timer) / 1000000; // Calculate delta time
  timer = micros();

#ifdef RESTRICT_PITCH // Eq. 25 and 26
  double roll  = atan2(accY, accZ) * RAD_TO_DEG;
  double pitch = atan(-accX / sqrt(accY * accY + accZ * accZ)) * RAD_TO_DEG;
#else // Eq. 28 and 29
  double roll  = atan(accY / sqrt(accX * accX + accZ * accZ)) * RAD_TO_DEG;
  double pitch = atan2(-accX, accZ) * RAD_TO_DEG;
#endif

  double gyroXrate = gyroX / 131.0; // Convert to deg/s
  double gyroYrate = gyroY / 131.0; // Convert to deg/s

#ifdef RESTRICT_PITCH
  // This fixes the transition problem when the accelerometer angle jumps
between -180 and 180 degrees
  if ((roll < -90 && kalAngleX > 90) || (roll > 90 && kalAngleX < -90)) {
    kalmanX.setAngle(roll);
    compAngleX = roll;
    kalAngleX = roll;
    gyroXangle = roll;
  } else
    kalAngleX = kalmanX.getAngle(roll, gyroXrate, dt); // Calculate the
angle using a Kalman filter

  if (abs(kalAngleX) > 90)
    gyroYrate = -gyroYrate; // Invert rate, so it fits the restriced
accelerometer reading
  kalAngleY = kalmanY.getAngle(pitch, gyroYrate, dt);
#else
  // This fixes the transition problem when the accelerometer angle jumps
between -180 and 180 degrees
  if ((pitch < -90 && kalAngleY > 90) || (pitch > 90 && kalAngleY < -90)) {
    kalmanY.setAngle(pitch);
    compAngleY = pitch;
    kalAngleY = pitch;
    gyroYangle = pitch;
  } else
    kalAngleY = kalmanY.getAngle(pitch, gyroYrate, dt); // Calculate the
angle using a Kalman filter

  if (abs(kalAngleY) > 90)
    gyroXrate = -gyroXrate; // Invert rate, so it fits the restriced
accelerometer reading
  kalAngleX = kalmanX.getAngle(roll, gyroXrate, dt); // Calculate the angle
using a Kalman filter
#endif

  gyroXangle += gyroXrate * dt; // Calculate gyro angle without any filter
  gyroYangle += gyroYrate * dt;
  //gyroXangle += kalmanX.getRate() * dt; // Calculate gyro angle using the
unbiased rate
  //gyroYangle += kalmanY.getRate() * dt;

  compAngleX = 0.93 * (compAngleX + gyroXrate * dt) + 0.07 * roll; //
Calculate the angle using a Complimentary filter
  compAngleY = 0.93 * (compAngleY + gyroYrate * dt) + 0.07 * pitch;

  // Reset the gyro angle when it has drifted too much
  if (gyroXangle < -180 || gyroXangle > 180)
    gyroXangle = kalAngleX;
  if (gyroYangle < -180 || gyroYangle > 180)
    gyroYangle = kalAngleY;

  /* Print Data */
#if 0 // Set to 1 to activate
  Serial.print(accX); Serial.print("\t");
  Serial.print(accY); Serial.print("\t");
  Serial.print(accZ); Serial.print("\t");
  Serial.print(gyroX); Serial.print("\t");
  Serial.print(gyroY); Serial.print("\t");
  Serial.print(gyroZ); Serial.print("\t");
  Serial.print("\t");
#endif

//Serial.print(roll); Serial.print("\t");
  //Serial.print(gyroXangle); Serial.print("\t");
  //Serial.print(compAngleX); Serial.print("\t");
  Serial.print(kalAngleX); Serial.print("\t");

  Serial.print("\t");

  //Serial.print(pitch); Serial.print("\t");
  //Serial.print(gyroYangle); Serial.print("\t");
  //Serial.print(compAngleY); Serial.print("\t");
  Serial.print(kalAngleY); Serial.print("\t");

#if 0 // Set to 1 to print the temperature
  Serial.print("\t");
  double temperature = (double)tempRaw / 340.0 + 36.53;
  Serial.print(temperature); Serial.print("\t");
#endif

  Serial.print("\r\n");
  delay(2);


//////////////////7


if (digitalRead(CONTROL_PIN) == LOW)


{

int valuey = kalAngleX;
 int valuex = kalAngleY;


 if (valuey >= -89 && valuey <= -85 )

 {stepper2.moveTo(-87 * cantidad);
    stepper2.run();}

else if (valuey >= -84 && valuey <= -80 )

 {stepper2.moveTo(-83 * cantidad);
    stepper2.run();}

else if (valuey >= -79 && valuey <= -75 )

 {stepper2.moveTo(-77 * cantidad);
    stepper2.run();}

else if (valuey >= -74 && valuey <= -70 )

 {stepper2.moveTo(-73 * cantidad);
    stepper2.run();}

else if (valuey >= -69 && valuey <= -65 )

 {stepper2.moveTo(-67 * cantidad);
    stepper2.run();}

else if (valuey >= -64 && valuey <= -60 )

 {stepper2.moveTo(-63 * cantidad);
    stepper2.run();}

else if (valuey >= -59 && valuey <= -55 )

 {stepper2.moveTo(-67 * cantidad);
    stepper2.run();}

else if (valuey >= -54 && valuey <= -50 )

 {stepper2.moveTo(-53 * cantidad);
    stepper2.run();}

else if (valuey >= -49 && valuey <= -45 )

 {stepper2.moveTo(-47 * cantidad);
    stepper2.run();}

else if (valuey >= -44 && valuey <= -40 )

 {stepper2.moveTo(-43 * cantidad);
    stepper2.run();}

else if (valuey >= -39 && valuey <= -35 )

 {stepper2.moveTo(-37 * cantidad);
    stepper2.run();}

else if (valuey >= -34 && valuey <= -30 )

 {stepper2.moveTo(-33 * cantidad);
    stepper2.run();}

else if (valuey >= -29 && valuey <= -25 )

 {stepper2.moveTo(-27 * cantidad);
    stepper2.run();}

else if (valuey >= -24 && valuey <= -20 )

 {stepper2.moveTo(-23 * cantidad);
    stepper2.run();}

else if (valuey >= -19 && valuey <= -15 )

 {stepper2.moveTo(-17 * cantidad);
    stepper2.run();}

else if (valuey >= -14 && valuey <= -10 )

 {stepper2.moveTo(-13 * cantidad);
    stepper2.run();}

else if (valuey >= -9 && valuey <= -5 )

 {stepper2.moveTo(-7 * cantidad);
    stepper2.run();}

else if (valuey >= -4 && valuey <= -1 )

 {stepper2.moveTo(-3 * cantidad);
    stepper2.run();}

else if (valuey >= 1 && valuey <= 5 )

 {stepper2.moveTo(3 * cantidad);
    stepper2.run();}

else if (valuey == 0)

 {stepper2.moveTo(0 * cantidad);
    stepper2.run();}



else if (valuey >= 6 && valuey <= 10 )

 {stepper2.moveTo(8 * cantidad);
    stepper2.run();}

else if (valuey >= 11 && valuey <= 15 )

 {stepper2.moveTo(13 * cantidad);
    stepper2.run();}

else if (valuey >= 16 && valuey <= 20 )

 {stepper2.moveTo(18 * cantidad);
    stepper2.run();}

else if (valuey >= 21 && valuey <= 25 )

 {stepper2.moveTo(23 * cantidad);
    stepper2.run();}

else if (valuey >= 26 && valuey <= 30 )

 {stepper2.moveTo(28 * cantidad);
    stepper2.run();}

else if (valuey >= 31 && valuey <= 35 )

 {stepper2.moveTo(33 * cantidad);
    stepper2.run();}

else if (valuey >= 36 && valuey <= 40 )

 {stepper2.moveTo(38 * cantidad);
    stepper2.run();}

else if (valuey >= 41 && valuey <= 45 )

 {stepper2.moveTo(43 * cantidad);
    stepper2.run();}

else if (valuey >= 46 && valuey <= 50 )

 {stepper2.moveTo(48 * cantidad);
    stepper2.run();}

else if (valuey >= 51 && valuey <= 55 )

 {stepper2.moveTo(53 * cantidad);
    stepper2.run();}

else if (valuey >= 56 && valuey <= 60 )

 {stepper2.moveTo(58 * cantidad);
    stepper2.run();}

else if (valuey >= 61 && valuey <= 65 )

 {stepper2.moveTo(63 * cantidad);
    stepper2.run();}

else if (valuey >= 66 && valuey <= 70 )

 {stepper2.moveTo(68 * cantidad);
    stepper2.run();}

else if (valuey >= 71 && valuey <= 85 )

 {stepper2.moveTo(73 * cantidad);
    stepper2.run();}



else if (valuey >= 86 && valuey <= 89 )

 {stepper2.moveTo(88 * cantidad);
    stepper2.run();}

//////////////////////////////
/////////////////////////////
/////////////////////////////


else {}


 if (valuex >= -89 && valuex <= -85 )

 {stepper1.moveTo(-87 * cantidad);
    stepper1.run();}

else if (valuex >= -84 && valuex <= -80 )

 {stepper1.moveTo(-83 * cantidad);
    stepper1.run();}

else if (valuex >= -79 && valuex <= -75 )

 {stepper1.moveTo(-77 * cantidad);
    stepper1.run();}

else if (valuex >= -74 && valuex <= -70 )

 {stepper1.moveTo(-73 * cantidad);
    stepper1.run();}

else if (valuex >= -69 && valuex <= -65 )

 {stepper1.moveTo(-67 * cantidad);
    stepper1.run();}

else if (valuex >= -64 && valuex <= -60 )

 {stepper1.moveTo(-63 * cantidad);
    stepper1.run();}

else if (valuex >= -59 && valuex <= -55 )

 {stepper1.moveTo(-67 * cantidad);
    stepper1.run();}

else if (valuex >= -54 && valuex <= -50 )

 {stepper1.moveTo(-53 * cantidad);
    stepper1.run();}

else if (valuex >= -49 && valuex <= -45 )

 {stepper1.moveTo(-47 * cantidad);
    stepper1.run();}

else if (valuex >= -44 && valuex <= -40 )

 {stepper1.moveTo(-43 * cantidad);
    stepper1.run();}

else if (valuex >= -39 && valuex <= -35 )

 {stepper1.moveTo(-37 * cantidad);
    stepper1.run();}

else if (valuex >= -34 && valuex <= -30 )

 {stepper1.moveTo(-33 * cantidad);
    stepper1.run();}

else if (valuex >= -29 && valuex <= -25 )

 {stepper1.moveTo(-27 * cantidad);
    stepper1.run();}

else if (valuex >= -24 && valuex <= -20 )

 {stepper1.moveTo(-23 * cantidad);
    stepper1.run();}

else if (valuex >= -19 && valuex <= -15 )

 {stepper1.moveTo(-17 * cantidad);
    stepper1.run();}

else if (valuex >= -14 && valuex <= -10 )

 {stepper1.moveTo(-13 * cantidad);
    stepper1.run();}

else if (valuex >= -9 && valuex <= -5 )

 {stepper1.moveTo(-7 * cantidad);
    stepper1.run();}

else if (valuex >= -4 && valuex <= -1 )

 {stepper1.moveTo(-3 * cantidad);
    stepper1.run();}


else if (valuex == 0 )

 {stepper1.moveTo(0 * cantidad);
    stepper1.run();}


else if (valuex >= 1 && valuex <= 5 )

 {stepper1.moveTo(3 * cantidad);
    stepper1.run();}

else if (valuex >= 6 && valuex <= 10 )

 {stepper1.moveTo(8 * cantidad);
    stepper1.run();}

else if (valuex >= 11 && valuex <= 15 )

 {stepper1.moveTo(13 * cantidad);
    stepper1.run();}

else if (valuex >= 16 && valuex <= 20 )

 {stepper1.moveTo(18 * cantidad);
    stepper1.run();}

else if (valuex >= 21 && valuex <= 25 )

 {stepper1.moveTo(23 * cantidad);
    stepper1.run();}

else if (valuex >= 26 && valuex <= 30 )

 {stepper1.moveTo(28 * cantidad);
    stepper1.run();}

else if (valuex >= 31 && valuex <= 35 )

 {stepper1.moveTo(33 * cantidad);
    stepper1.run();}

else if (valuex >= 36 && valuex <= 40 )

 {stepper1.moveTo(38 * cantidad);
    stepper1.run();}

else if (valuex >= 41 && valuex <= 45 )

 {stepper1.moveTo(43 * cantidad);
    stepper1.run();}

else if (valuex >= 46 && valuex <= 50 )

 {stepper1.moveTo(48 * cantidad);
    stepper1.run();}

else if (valuex >= 51 && valuex <= 55 )

 {stepper1.moveTo(53 * cantidad);
    stepper1.run();}

else if (valuex >= 56 && valuex <= 60 )

 {stepper1.moveTo(58 * cantidad);
    stepper1.run();}

else if (valuex >= 61 && valuex <= 65 )

 {stepper1.moveTo(63 * cantidad);
    stepper1.run();}

else if (valuex >= 66 && valuex <= 70 )

 {stepper1.moveTo(68 * cantidad);
    stepper1.run();}

else if (valuex >= 71 && valuex <= 85 )

 {stepper1.moveTo(73 * cantidad);
    stepper1.run();}



else if (valuex >= 86 && valuex <= 89 )

 {stepper1.moveTo(88 * cantidad);
    stepper1.run();}









else {}

//////_---


}


else


{

if (digitalRead(LEFT_PIN) == 0) {

    stepper2.moveTo(pos);
    stepper2.run();
    }

   else if (digitalRead(RIGHT_PIN) == 0) {

    stepper2.moveTo(-pos);
    stepper2.run();
    }

   else if (digitalRead(STOP_PIN) == 0) {

    stepper2.moveTo(0);
    stepper2.run();
    }



}





}

**Comment by Denvi** [comment]
Проблема может быть в отсутствии файлов "i2c.ino" и/или "kalman.h" в папке с приведенным вами .ino файлом.
