### ISSUE TITLE
Feed override disabled when not running program

### ISSUE THREAD

**Issue by DEF7** [Denvi/grblControl#30]
I suppose this is just more of a question about QT, which all of my experience with comes from working with the grblControl code: I cannot figure out how certain things like the feed override slider and the spindle speed are being disabled (ie: 'grayed out') when a program isn't running. I have discovered how most things are being enabled/disabled on the UI, but these things seem to be linked together somehow in a way that I cannot figure out that is controlled by whether or not a program is actively being sent to the CNC.

 Thanks :)

**Comment by Denvi** [comment]
Some signals/slots can be set up in form designer. Designer has several editing modes:
1) Widgets editing.
2) Signals/slots.
3) Buddies.
4) Tabstops.

For each mode there is appropriate buttons in top toolbar, or you can use shortcuts for first two modes <F3>, <F4>.

Feed override & spindle speed widgets "enabled" slots are connected to "Keyboard control" checkbox "toggle" signal in designer.
