### ISSUE TITLE
GRBLControl dont start on fresh WinXP

### ISSUE THREAD

**Issue by Zyrusthc** [Denvi/grblControl#31]
This is a fresh Windows XP installation with Service Pack 3 installed. Unfortunately GRBLControl not start . What can I do? Athlon XP2400 2GB Ram

![screenshot 2016-02-04 02 29 05_2](https://cloud.githubusercontent.com/assets/17056967/12803017/9b83ce64-cae7-11e5-8313-199b61e38a58.png)

**Comment by Denvi** [comment]
1) grblControl version you try to start?
2) What video card & drivers you using?
3) Whether tried 0.5.2 version of grblControl for Windows XP?

**Comment by Zyrusthc** [comment]
I have tried all versions the same everywhere .
Radeon 9200SE and last driver from ATI Page

**Comment by Denvi** [comment]
I believe grblControl require video card with OpenGL 2.0 support (Radeon 9200SE supports OpenGL 1.4).

But in your case the reason most likely in the processor, which doesn't support SSE2 instructions.
> Athlon XP2400

**Comment by Zyrusthc** [comment]
ahh okay thx ,like I have in photoshop also because of the lack sse2 thing .
