### ISSUE TITLE
Edge and  hole center finder 

### ISSUE THREAD

**Issue by milezdr** [Denvi/grblControl#37]
Hi Denvi you have done awesome work with grblcontrol especially with height map probing.So I wonder if it's possible for you to make edge and hole center finder with this probing routines   http://www.timeguy.com/cradek/01262579508  ?

**Comment by Denvi** [comment]
Hello, it's possible. 
But neither grbl firmware nor grblControl app doesn't support RS274/NGC parameters (variables) now.
I don't think that this functionality will be realized soon.
Anyway I will think over the described functions.

**Comment by milezdr** [comment]
I talked to the Grbl guy Chamnit what you told me  and he said this : " parameters/variables are easy to simulate with any modern programming language (arguably much better). bCNC does that with their Python-based GUI. If you can program Python, then you can install a plug-in (macro program)."

**Comment by Denvi** [comment]
I can do it without Python. 
It is a matter of time and desires.
