### ISSUE TITLE
Don't work with Raspberry/Raspbian !?

### ISSUE THREAD

**Issue by ArtFaks** [Denvi/grblControl#4]
Hi,

Thanks for your hard work and for your fabulous dev ;-)

This issue post just for ask, if work with Linux, why don't work with Raspian ?

**Comment by Denvi** [comment]
Program starts on raspian, but there is performance issues on wich i working now.
Huge problem is qt widgets application with QOpenGLWidget as g-code visualizer. I have bugs with it for now. Try to build/start "qopenglwidget" example from qt5 (version >= 5.4) sdk on your raspberry and interract with widgets on form.

**Comment by ArtFaks** [comment]
Ok, thanks Denvi ;-)
