### ISSUE TITLE
does not work visualization on versions higher than 0.5.2 for xp

### ISSUE THREAD

**Issue by Lenrockus** [Denvi/grblControl#40]
since I had install fresh copy of windows 7 x32,  I'm not able to run correctly grblcontrol (except xp version), visualization doesn't work anymore. what else software should I install to get it work?

**Comment by Denvi** [comment]
OpenGL driver.

**Comment by Denvi** [comment]
Any motions? 
What graphics card you have installed?

**Comment by Lenrockus** [comment]
My graphic card is an old intel 965 express on a compaq presario notebook.it supports only opengl 1.5 and 2.0. When updated to  2.0 grblcontrol crashes on startup. At 1.5 it doesn't show any visualisation

**Comment by Lenrockus** [comment]
My graphic card is an old intel 965 express on a compaq presario notebook.it supports only opengl 1.5 and 2.0. When updated to  2.0 grblcontrol crashes on start.

**Comment by Denvi** [comment]
"grblControl" works on windows xp well from 0.6. There is no need to compile separate version.
Can you post "DebugView" program output? Refer to #28.

**Comment by Lenrockus** [comment]
I will do it as soon as possible, curently I'm not in my home city. Thank you .
