### ISSUE TITLE
Make with grblControl

### ISSUE THREAD

**Issue by Xav83130** [Denvi/grblControl#43]
No comments.

![PCB](http://pix.slic.it/p/6m6)

![PCB2](http://pix.slic.it/p/6m7)

**Comment by Denvi** [comment]
Maybe after all comment?

Quality of milling leaves much to be desired. 
I see milling was carried out with insufficient deepening.
Besides, problems with mechanics of the machine are possible.
What router are you using?

**Comment by Xav83130** [comment]
indeed,
I have a lot of small problems to settle.
but the circuit is (I hope) functional.

I use a home made machine (with little financial means).
link to my machine: [https://github.com/Xav83130/Mini-CNC](url)

**Comment by Denvi** [comment]
Good CNC.
X-Z carriage is weak place. It is necessary to make of metal to get rid of uneven lines when milling.

**Comment by Xav83130** [comment]
yes, I also have a little gap in the transmission (despite the backlash)
simple threaded rods.
Finally, with all this I'm pretty happy with the result.
Thank you for grblControl is a good tool.

**Comment by Denvi** [comment]
Thanks. It is pleasant to hear that the program was useful.

**Comment by Xav83130** [comment]
Hello,
I tried to follow your advice, so I redid the circuit.
it looks better ...
![PCB](http://pix.slic.it/p/6ny)
![PCB](http://pix.slic.it/p/6nz)
