### ISSUE TITLE
GRBL stuck during work

### ISSUE THREAD

**Issue by ojdas** [Denvi/grblControl#47]
Hi,

I have an issue when I'm using this tool during cutting ply.
I have observed very strange situation - grbl stuck during ordinary works.
It is very annoying when the whole job we need do once again :(
As well as there is no option to restart GRBL if stuck we need reset all and move project again from the begging.

Do you have any idea why I have an issue?
Did you have the same or similar problem?

thx.
Piotr

**Comment by Denvi** [comment]
Hello.

- What CNC you using?
- How it's stucks? Steppers just stopes? Spindle stops? Any messages in console panel of grblControl? Post screenshot of main window when stuck.
- Try to do idle running on same G-code program with spindle turned off.
- CNC have end-stops? Try idle running with disconnected end-stops.

**Comment by ojdas** [comment]
Hi Denvi,

I'm using Arduino CNC shield V3
Steppers just stops, spindle is not connected to shield and power supply for spindle is separate.
I have end-stops so I will try to disconnect during running but it is quite strange because during running all end-stops are not touched.
Previously I have used GRBLControl v8.1 today I will try 8.3 maybe here is an issue?

Thanks,
Piotr

**Comment by Denvi** [comment]
> but it is quite strange because during running all end-stops are not touched.

There are suspicions that has put in hindrances on wires.

> Previously I have used GRBLControl v8.1 today I will try 8.3 maybe here is an issue?

I don't think there is any differences in that versions releative to your problem.
