### ISSUE TITLE
Prebuilt binary fails to launch on Ubuntu 14.04

### ISSUE THREAD

**Issue by powercycle** [Denvi/grblControl#5]
Tried downloading the pre-built binary and it fails at command line execution.

There is an Error, but the message that comes after doesn't show anything intelligible.

Also, tried cloning the repo to build it myself, but no make files.

How should I build this codebase on my Ubuntu machine?

Thanks for your guidance.

**Comment by Denvi** [comment]
Hello, can you copy/paste console messages before error?
To build from source code you need install Qt5 (latest version recommended, >=5.3 needed to use serial port) on your machine (https://wiki.qt.io/Install_Qt_5_on_Ubuntu). 
Then in command line:
1) cd <path_to_source_code>
2) qmake
3) make

**Comment by powercycle** [comment]
Here is the output when trying to run the grblControl binary.
![screenshot - 09202015 - 11 53 35 am](https://cloud.githubusercontent.com/assets/2614846/9982602/5d4b8ef8-5f8e-11e5-85df-c2bbecbe9d7f.png)

**Comment by powercycle** [comment]
I apologize..I did not mean to close this issue.

**Comment by Denvi** [comment]
Fixed in version 0.6.

**Comment by powercycle** [comment]
I'll give it a shot this week.

**Comment by powercycle** [comment]
This worked great!   Thanks!
