### ISSUE TITLE
Language Pref

### ISSUE THREAD

**Issue by patgadget** [Denvi/grblControl#54]
Hi,
thanks for the Wonderful Program.
i would like to create some print screen of the program and add information in you wiki page.
but my computer is in french and your program adopt it and i cannot find a way to change the language to English.

Is there a way to change the language on your software?
Thanks a lot again for grblControl.

Pat Gadget.

**Comment by Denvi** [comment]
Hello, application has english language by default.

So easiest way - to rename "translations" folder.

![iss54_1](https://cloud.githubusercontent.com/assets/5119037/15396339/14de720e-1df5-11e6-9df1-1d8af31f1033.png)

**Comment by patgadget** [comment]
Perfect, i can figure out how to insert a print screen,
is there and easy way? or could you send me to a explanatory page?
Hope my Wiki Pages Helps?
Thanks

**Comment by Denvi** [comment]
I think we need store screenshots on github, you can clone repo & add all needed screenshots to "wiki/images" folder through the pull request.
