### ISSUE TITLE
How restore XYZ key work?

### ISSUE THREAD

**Issue by Robyrob** [Denvi/grblControl#56]
Hello. Thank you for your project and the work you have done. I’m new to CNC and I’m beginning to use my new CNC with your software.
I have a question for you, I didn’t understand myself:
In version 0.8.3 Restore XYZ key did move the CNC to home position (relative) just for X and Y coordinates. Why not Z?
And now, with new version 0.8.4, this key just restore offset and don’t move CNC
How can I move the CNC step motors to home (relative 0,0,0)?
Many thanks Roberto

**Comment by Denvi** [comment]
Hello.

> How can I move the CNC step motors to home (relative 0,0,0)?

Type in command line:

~~~
G0X0Y0Z0
~~~
