### ISSUE TITLE
Error in g code calibrator

### ISSUE THREAD

**Issue by zagranichnyy** [Denvi/grblControl#59]
You have configured the calibrator has a bug which leads to malfunction

**Comment by Denvi** [comment]
Please, describe a problem in more detail.

**Comment by zagranichnyy** [comment]
Если запустить калибровку, а после обнулить и запустить задание, ось z поднимается вверх и станок движется по Y пока не упрется в край

**Comment by Denvi** [comment]
Под "обнулить" вы что имеете в виду?

**Comment by Denvi** [comment]
Думаю будет сложно разобраться в чем дело без пошагового (со снимками экрана) объяснения как возникает ошибка.
