### ISSUE TITLE
grbl control won't start on lubuntu

### ISSUE THREAD

**Issue by leonardocecchin** [Denvi/grblControl#61]
Hi, I cannot open the software on lubuntu latest version, here is a photo of the terminal
Thanks, leonardo

**Comment by leonardocecchin** [comment]
![Uploading WP_20160610_15_15_55_Pro.jpg…]()

**Comment by leonardocecchin** [comment]
![wp_20160610_15_15_55_pro](https://cloud.githubusercontent.com/assets/19857921/15983692/9578ad18-2fb0-11e6-91a1-d03204225307.jpg)
Here is it, I started both with superuser or not, the error remains the same, also with older versions of the software

**Comment by Denvi** [comment]
Please post output from the following command:

~~~
ldd -v grblcontrol
~~~

And what hardware you use (cpu, graphics card)?

**Comment by leonardocecchin** [comment]
![2016-06-10-074243_1024x768_scrot](https://cloud.githubusercontent.com/assets/19857921/15986661/5c7f8362-300d-11e6-9147-a36d023bfedb.png)
![2016-06-10-074254_1024x768_scrot](https://cloud.githubusercontent.com/assets/19857921/15986663/5cb129b2-300d-11e6-9e30-4f0832073ea9.png)
![2016-06-10-074306_1024x768_scrot](https://cloud.githubusercontent.com/assets/19857921/15986664/5cb758dc-300d-11e6-8b16-acdb710e1fa8.png)
![2016-06-10-074320_1024x768_scrot](https://cloud.githubusercontent.com/assets/19857921/15986665/5cbcc89e-300d-11e6-9d3f-9301edc0c186.png)
![2016-06-10-074330_1024x768_scrot](https://cloud.githubusercontent.com/assets/19857921/15986666/5cc7a296-300d-11e6-9ec9-9dd4092ad304.png)
![2016-06-10-074339_1024x768_scrot](https://cloud.githubusercontent.com/assets/19857921/15986667/5ccdc13a-300d-11e6-9b65-ecee46cda3db.png)
![2016-06-10-074345_1024x768_scrot](https://cloud.githubusercontent.com/assets/19857921/15986662/5ca0144c-300d-11e6-9633-208d535dc3c9.png)
![2016-06-10-074355_1024x768_scrot](https://cloud.githubusercontent.com/assets/19857921/15986668/5cd4771e-300d-11e6-92ae-1bd14aa54c73.png)
 These are the screenshots of the output, the pc is an old Intel Pentium that natively was running windows XP, anthe graphics card is the original one, there isn't a code or name or something
 Thanks

**Comment by Denvi** [comment]
Install Glxinfo and check supported OpenGL version please.

~~~
sudo apt-get install mesa-utils
glxinfo | grep "OpenGL version"
~~~

CPU info also needed:

~~~
cat /proc/cpuinfo
~~~

**Comment by jflapao** [comment]
Hello is possible your software work on a raspberry pi the model B with 512mb or any other more powerfull

**Comment by Denvi** [comment]
Not for now. All operation in this direction is frozen.
